apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: install-maximo-app-suite-9.1.x
spec:
  workspaces:
    - name: ws
  params:
    - name: mas-catalog-version
      type: string
      default: "v9-250731-amd64"
    - name: mas-instance-id
      type: string
      default: "mas1"
    - name: mas-workspace-id
      type: string
      default: "ws1"
    - name: mas-workspace-name
      type: string
      default: "workspace"
    - name: mas-channel
      type: string
      default: "9.1.x"
    - name: ibm-entitlement-key
      type: string
    - name: uds-email
      type: string
      default: "john@email.com"
    - name: uds-firstname
      type: string
      default: "john"
    - name: uds-lastname
      type: string
      default: "barney"
    - name: storage-rwo
      type: string
      default: "ocs-external-storagecluster-ceph-rbd"
    - name: storage-rwx
      type: string
      default: "ocs-external-storagecluster-cephfs"
    - name: storage-pipeline
      type: string
      default: "ocs-external-storagecluster-cephfs"
    - name: storage-accessmode
      type: string
      default: "ReadWriteMany"

    # Additional params to support install-mas task
    - name: license-file
      type: string
      default: "license.dat"
    - name: dro-namespace
      type: string
      default: "redhat-marketplace"
    - name: mongodb-namespace
      type: string
      default: "mongoce"

    # Feature flags
    - name: enable-iot
      type: string
      default: "false"
    - name: iot-channel
      type: string
      default: "9.1.x"

    - name: enable-monitor
      type: string
      default: "false"
    - name: monitor-channel
      type: string
      default: "9.1.x"

    - name: enable-optimizer
      type: string
      default: "false"
    - name: optimizer-channel
      type: string
      default: "9.1.x"
    - name: optimizer-plan
      type: string
      default: "full"

    - name: enable-predict
      type: string
      default: "false"
    - name: predict-channel
      type: string
      default: "9.1.x"

    - name: enable-mref
      type: string
      default: "false"
    - name: mref-channel
      type: string
      default: "9.1.x"

    - name: enable-manage
      type: string
      default: "false"
    - name: manage-channel
      type: string
      default: "9.1.x"
    - name: enable-manage-demo-data
      type: string
      default: "false"
    - name: manage-jdbc
      type: string
      default: "workspace-application"
    - name: manage-components
      type: string
      default: "base=latest,health=latest,spatial=latest,strategize=latest,serviceprovider=latest,utilities=latest,hse=latest,aip=latest"
    - name: manage-server-bundle-size
      type: string
      default: "jms"
    - name: manage-base-language
      type: string
      default: "EN"
    - name: manage-server-timezone
      type: string
      default: "GMT"

    # DB2
    - name: db2-channel
      type: string
      default: "v110509.0"
    - name: db2-namespace
      type: string
      default: "db2u"
    - name: db2-type
      type: string
      default: "db2wh"
    - name: db2-timezone
      type: string
      default: "GMT"
    - name: db2-cpu-requests
      type: string
      default: "4000m"
    - name: db2-cpu-limits
      type: string
      default: "6000m"
    - name: db2-memory-requests
      type: string
      default: "8Gi"
    - name: db2-memory-limits
      type: string
      default: "12Gi"
    - name: db2-backup-storage
      type: string
      default: "100Gi"
    - name: db2-data-storage
      type: string
      default: "100Gi"
    - name: db2-logs-storage
      type: string
      default: "100Gi"
    - name: db2-meta-storage
      type: string
      default: "20Gi"
    - name: db2-temp-storage
      type: string
      default: "100Gi"

    # Kafka
    - name: enable-kafka
      type: string
      default: "true"
    - name: kafka-provider
      type: string
      default: "strimzi"
    - name: kafka-namespace
      type: string
      default: "strimzi"
    - name: kafka-version
      type: string
      default: "3.9.0"

  tasks:
    - name: update-image-registry
      taskRef:
        name: update-image-registry
      params:
        - name: registry-storageclass
          value: $(params.storage-rwx)

    - name: get-ibm-entitlement-key
      taskRef:
        name: ibmcloud-secrets-manager-get
        kind: Task
      retries: 2
      params:
        - name: KEY_ID
          value: 968d7819-f2c5-7b67-c420-3c6bfd51521e
        - name: SECRETS_MANAGER_ENDPOINT_URL
          value: >-
            https://afa20521-cd75-4864-843f-e59fd0ffd49d.us-south.secrets-manager.appdomain.cloud

    - name: get-maximo-license
      taskRef:
        name: get-maximo-license
      workspaces:
        - name: ws
          workspace: ws

    - name: run-install-mas
      runAfter:
        - get-maximo-license
        - update-image-registry
        - get-ibm-entitlement-key
      taskRef:
        name: install-mas
      workspaces:
        - name: ws
          workspace: ws
      params:
        - name: mas-catalog-version
          value: $(params.mas-catalog-version)
        - name: mas-instance-id
          value: $(params.mas-instance-id)
        - name: mas-workspace-id
          value: $(params.mas-workspace-id)
        - name: mas-workspace-name
          value: $(params.mas-workspace-name)
        - name: ibm-entitlement-key
          value: $(tasks.get-ibm-entitlement-key.results.secret-value)
        - name: license-file
          value: $(workspaces.ws.path)/license.dat
        - name: uds-email
          value: $(params.uds-email)
        - name: uds-firstname
          value: $(params.uds-firstname)
        - name: uds-lastname
          value: $(params.uds-lastname)
        - name: storage-rwo
          value: $(params.storage-rwo)
        - name: storage-rwx
          value: $(params.storage-rwx)
        - name: storage-pipeline
          value: $(params.storage-pipeline)
        - name: storage-accessmode
          value: $(params.storage-accessmode)
        - name: dro-namespace
          value: $(params.dro-namespace)
        - name: mongodb-namespace
          value: $(params.mongodb-namespace)
        - name: mas-channel
          value: $(params.mas-channel)
        - name: enable-iot
          value: $(params.enable-iot)
        - name: iot-channel
          value: $(params.iot-channel)
        - name: enable-monitor
          value: $(params.enable-monitor)
        - name: monitor-channel
          value: $(params.monitor-channel)
        - name: enable-optimizer
          value: $(params.enable-optimizer)
        - name: optimizer-channel
          value: $(params.optimizer-channel)
        - name: optimizer-plan
          value: $(params.optimizer-plan)
        - name: enable-predict
          value: $(params.enable-predict)
        - name: predict-channel
          value: $(params.predict-channel)
        - name: enable-mref
          value: $(params.enable-mref)
        - name: mref-channel
          value: $(params.mref-channel)
        - name: enable-manage
          value: $(params.enable-manage)
        - name: enable-manage-demo-data
          value: $(params.enable-manage-demo-data)
        - name: manage-channel
          value: $(params.manage-channel)
        - name: manage-jdbc
          value: $(params.manage-jdbc)
        - name: manage-components
          value: $(params.manage-components)
        - name: manage-server-bundle-size
          value: $(params.manage-server-bundle-size)
        - name: manage-base-language
          value: $(params.manage-base-language)
        - name: manage-server-timezone
          value: $(params.manage-server-timezone)
        - name: db2-channel
          value: $(params.db2-channel)
        - name: db2-namespace
          value: $(params.db2-namespace)
        - name: db2-type
          value: $(params.db2-type)
        - name: db2-timezone
          value: $(params.db2-timezone)
        - name: db2-cpu-requests
          value: $(params.db2-cpu-requests)
        - name: db2-cpu-limits
          value: $(params.db2-cpu-limits)
        - name: db2-memory-requests
          value: $(params.db2-memory-requests)
        - name: db2-memory-limits
          value: $(params.db2-memory-limits)
        - name: db2-backup-storage
          value: $(params.db2-backup-storage)
        - name: db2-data-storage
          value: $(params.db2-data-storage)
        - name: db2-logs-storage
          value: $(params.db2-logs-storage)
        - name: db2-meta-storage
          value: $(params.db2-meta-storage)
        - name: db2-temp-storage
          value: $(params.db2-temp-storage)
        - name: enable-kafka
          value: $(params.enable-kafka)
        - name: kafka-provider
          value: $(params.kafka-provider)
        - name: kafka-namespace
          value: $(params.kafka-namespace)
        - name: kafka-version
          value: $(params.kafka-version)
